workshopapps/realxchangerate.web

frontend/client/src/components/styles/Contact.styled.js

fix: rem issue

---

frontend/client/src/Pages/CurrencyEncyclopedia/CurrencyEncyclopedia.jsx
frontend/client/src/components/encyclopedia/currencyenclopedia/EnCurrency.jsx
frontend/client/src/components/encyclopedia/currencyenclopedia/EnCurrencyStyles.jsx
frontend/client/src/components/encyclopedia/enCountryletter/EnCountryLetter.jsx
frontend/client/src/components/encyclopedia/enCountryletter/EnCountryStyles.jsx
frontend/client/src/components/encyclopedia/encurrenciesrate/EnRateStyles.jsx
frontend/client/src/components/encyclopedia/encurrencychange/EnCurrenChStyles.jsx
frontend/client/src/components/encyclopedia/encurrencychange/EnCurrencyCh.jsx
frontend/client/src/components/encyclopedia/encyinfo/EnInfo.jsx
frontend/client/src/components/encyclopedia/encyinfo/EnInfoStyles.jsx
frontend/client/src/components/encyclopedia/endetail/EnDetail.jsx
frontend/client/src/components/encyclopedia/endetail/EnDetailStyles.jsx
frontend/client/src/components/encyclopedia/enpopularcurrency/EnPopCurrencies.jsx
frontend/client/src/components/encyclopedia/enpopularcurrency/EncPopularStyles.jsx

Encyclopedia page

---

frontend/client/src/components/NavComponent.jsx
frontend/client/src/components/styles/NavBar.styled.jsx

This Restores Header back to normal, wrongly positioned on mobile screens

Restore Header 

---

frontend/client/src/Pages/OnlineAdvertising/OnlineAdvertising.jsx

This PR fixes some minor styling issues on the page
I fixed spacing and width overflowing issues.
Before
After

fix: minor styling issues

---

backend/app/main.py

backend cross-origin implementation

set cors to accept from our frontend origins

---

backend/app/api/v1/admin.py
backend/app/schemas/__init__.py
backend/app/schemas/rate.py

linear : BAC-55 (https://linear.app/team-bevel/issue/BAC-55/build-an-endpoint-to-update-currency-and-rates)
An endpoint to UPDATE currency :
-This endpoint recives the details(iso_code, symbol, country) to update a currency.
-It requires the iso code of the currency that will be updated
An endpoint to UPDATE rates:
-This endpoint recives details to update a currency's rate. 
-It finds the rate in the database by locating the currency associated with it using the required  iso code provided

Feat bac 55 an endpoint to update currency and rates

---

.gitignore
frontend/admin/package-lock.json
frontend/admin/package.json

- fixed node modules error
- installed axios in the admin app

Feat dashboard implementation

---

backend/app/api/v1/currency.py

* Update get_all_currencies_and_rates function to include the latest rate

Update get_all_currencies_and_rates function to include the latest rate

---

frontend/admin/package-lock.json

- updated currency overview page
- implemented the API

Fro 71 currency overview page

---

frontend/admin/src/component/SidebarComponent/nav/SidebarNavigation.styled.js
frontend/admin/src/store/actions/dashboardActions.js

-Worked on the Trending page Api
- Used redux toolkit to manage authentication state

feat(FRO-69): tredingData api integrated

---

frontend/client/src/Pages/Home/components/Table2.jsx
frontend/client/src/components/home/Convert.jsx
frontend/client/src/components/home/home.module.css

rounded table numbers to 2 decimal places
added the base currency style for the when currencies are switched

Fro 75 landing convert

---

frontend/client/src/components/home/Convert.jsx

the input fields are made to switch from column to row as the switch button switches from vertical to horizontal accordingly

style: set conversion switching to be responsive

---

frontend/admin/src/component/TrendingDataComponent/table/DataTable.jsx

- removes permanent loading state

feat: removes permenant loading state

---

frontend/client/src/App.js
frontend/client/src/Pages/Home/Home.jsx
frontend/client/src/components/home/Convert.jsx
frontend/client/src/components/home/Hero.jsx
frontend/client/src/components/home/home.module.css

style: 
styled homepage better (fixed hero and convert alignment and padding, hero font-size, etc) 
refactor: removed unused code, added spaces between functions

style and refactor

---

frontend/client/src/Main.jsx
frontend/client/src/components/Drawer.jsx
frontend/client/src/redux/features/Reducers/serviceActions.js

Changed ip storage location from local storage to session storage
fixed drawer links in mobile view

chore: changed storage location of ip, link fix

---

checks.json
frontend/client/package-lock.json
frontend/client/src/Pages/Home/Home.jsx
frontend/client/src/Pages/Home/components/Table2.jsx
frontend/client/src/Pages/Partnerships/PartnershipsHero.jsx
frontend/client/src/Pages/Partnerships/styles/HeroSection.styles.js
frontend/client/src/components/home/Hero.jsx
frontend/client/src/components/home/home.module.css

What I. did:
Made the live rates table look exactly as it suppose to be on the design

Fix  adjust live rates table to match with design

---

backend/app/models/currency.py
backend/app/schemas/currency.py

Reverts workshopapps/realxchangerate.web#239

Revert "Refactor/STR-31 update currency model to include currency name"

---

frontend/client/.env
frontend/client/package-lock.json
frontend/client/src/Main.jsx
frontend/client/src/components/NavComponent.jsx
frontend/client/src/redux/features/Reducers/serviceActions.js
frontend/client/src/redux/features/Utils/Axios/axios.js

This pull request:
- added the functionality of geolocation for the webapp
- implemented location endpoint
- Changed the base url to match the current server
- come minor fixes
Linear Link : https://linear.app/team-bevel/issue/FRO-22/implement-location-endpoint-on-the-website

Fe 68 contact historical currency

---

frontend/client/package-lock.json
frontend/client/src/App.js
frontend/client/src/Pages/PrivacyPolicy/PrivacyPolicy.js
frontend/client/src/Pages/PrivacyPolicy/component/Introduction.jsx
frontend/client/src/Pages/PrivacyPolicy/component/PersonalData.jsx
frontend/client/src/Pages/PrivacyPolicy/style/Privacy.styled.js
frontend/client/src/Pages/index.js
frontend/client/src/components/Footer.jsx

Implemented the privacy policy page

Str 94/privacy policy

---

backend/app/api/v1/admin.py
backend/app/api/v1/currency.py
backend/app/crud/currency.py
backend/app/schemas/currency.py

linear : BAC-8 (https://linear.app/team-bevel/issue/BAC-8/create-an-endpoint-that-searches-for-a-currency-based-on-the-currency)
An endpoint that searches for a currency using either the currency name or country name:
-This endpoint receives a keyword(which can either be the currency name or country name).
-It then returns the currency that matches

feat-BAC-8-A-GET-endpoint-that-searches-for-a-currency-based-on-the-currency-name-or-country-name

---

frontend/client/src/Pages/Home/data.js
frontend/client/src/components/Loader.jsx
frontend/client/src/components/home/Convert.jsx

Fix: Fix Convert Input spacing

---

frontend/client/src/Pages/Partnerships/Partnerships.jsx

Reverts workshopapps/realxchangerate.web#306

Revert "Frontend"

---

frontend/client/src/Pages/Partnerships/Partnerships.jsx

Reverts workshopapps/realxchangerate.web#312

Revert "Revert "Frontend""

---

frontend/client/src/Pages/Partnerships/Partnerships.jsx
frontend/client/src/Pages/Partnerships/PartnershipsHero.jsx
frontend/client/src/Pages/Partnerships/ReferralPartners.jsx
frontend/client/src/Pages/Partnerships/WhyChoose.jsx
frontend/client/src/Pages/Partnerships/assets/data.jsx
frontend/client/src/Pages/Partnerships/styles/WhyChoose.styles.js

What I did:
1. I implemented the design assigned to me by my designer on the partnership page.
2. fix positioning and alignment for the page.
3. added smooth scroll functionality. 
4. Fix a bug found on the page.

fix: update the partners page

---

frontend/client/src/Pages/PrivacyPolicy/style/Privacy.styled.js

adjusted the main section alignment to match the header

refactor: width and margin

---

frontend/admin/src/component/HeaderComponent/search/HeaderSearch.styled.js
frontend/admin/src/pages/CreateCurrency/CreateCurrency.jsx
frontend/admin/src/pages/CreateCurrency/Modal.jsx
frontend/admin/src/pages/CreateCurrency/cardStyles.js
frontend/admin/src/pages/CreateCurrency/currStyles.js

Adjust add currency button, text shadows, improve responsiveness, adjust search box size on admin dashboard page and fix texts discrepancies

FRO-524/dashboard improve

---

frontend/client/src/App.js
frontend/client/src/Pages/PrivacyPolicy/style/Privacy.styled.js
frontend/client/src/Pages/StudentAmbassador/components/HeroSection.jsx
frontend/client/src/Pages/StudentAmbassadorForm/StudentAmbassadorForm.js
frontend/client/src/Pages/StudentAmbassadorForm/components/ApplicationForm.jsx
frontend/client/src/Pages/StudentAmbassadorForm/style/Application.style.js
frontend/client/src/Pages/index.js

Student ambassador aplication form

Fro-43/student ambassador application

---

backend/app/api/v1/rate.py
backend/app/main.py

added an exception handler

---

frontend/admin/package-lock.json
frontend/admin/package.json
frontend/admin/src/App.js
frontend/admin/src/component/ComplaintPage/ComplaintPageLayout.jsx
frontend/admin/src/component/UserComplaintsComponent/UserComplaintsLayout.jsx

feat: adds react-toastify

---

frontend/admin/src/component/TrendingDataComponent/table/DataTable.jsx

https://linear.app/team-bevel/issue/FRO-11/implement-trending-data-redesign

feat: integrate trending data api

---

frontend/client/src/Pages/FileComplaints/components/ComplaintForm/ComplaintForm.js

Reverts workshopapps/realxchangerate.web#396

Revert "fix: fixed axios post request object convention"

---

backend/app/api/v1/contact.py
backend/app/crud/contact.py

linear : BAC-42 (https://linear.app/team-bevel/issue/BAC-42/create-a-get-endpoint-to-return-contact-us-details-for-individual-user)
An endpoint that returns a specific user contact details from the database using its associated id

Bac 42 create a get endpoint to return contact us details for individual user by

---

backend/app/api/v1/complaints.py
backend/app/crud/complaints.py

linear : BAC-40 (https://linear.app/team-bevel/issue/BAC-40/create-a-get-endpoint-to-get-an-individual-complaint-by-id)
An endpoint that returns a specific user complaints details from the database using its associated id

BAC-40-A-GET-endpoint-to-get-an-individual-complaint-by-id

---

frontend/admin/src/component/ComplaintPage/ComplaintPageLayout.jsx
frontend/admin/src/component/UserComplaintsComponent/UserComplaintsLayout.jsx

feat: fixes static data

---

frontend/admin/src/component/ComplaintPage/ComplaintPageLayout.jsx

- adds toast for status change only

Feat admin api

---

frontend/admin/src/pages/CreateCurrency/AddForm.jsx
frontend/admin/src/pages/CreateCurrency/EditForm.jsx

Fix: Edit functionality

---

frontend/admin/src/pages/faqs/Cards.jsx

Str 4 admin faqs

---

frontend/client/src/Pages/FaqOverview/FaqOverview.jsx

- integrates 'get-in-touch' to button

Feat client faq2

---

frontend/client/src/Pages/ApplyToAdvertise/components/ApplicationForm.jsx
frontend/client/src/Pages/ApplyToAdvertise/style/ApplyToAdvertisement.style.js
frontend/client/src/Pages/News/News.jsx
frontend/client/src/Pages/News/components/Selector.jsx
frontend/client/src/components/NavComponent.jsx
frontend/client/src/redux/features/Reducers/serviceActions.js
frontend/client/src/redux/features/Utils/Axios/apis/index.js
frontend/client/src/redux/features/Utils/Axios/axios.js

This PR contains:
- implementation of apply to advertise endpoint
- some bug fix in news page

feat: FRO-34-Implemented apply-to-advertise endpoint

---

frontend/admin/package-lock.json
frontend/admin/package.json
frontend/admin/src/App.js
frontend/admin/src/pages/affiliates/Affiliates.jsx
frontend/admin/src/pages/affiliates/firebase.js
frontend/client/package-lock.json
frontend/client/package.json
frontend/client/src/Pages/PartnersForm/AffiliatePartners/Affiliate.jsx
frontend/client/src/Pages/PartnersForm/AffiliatePartners/database.js

setup firestore db for affiliates data
client can now send affiliates' data submissions to firestore 
admin can now retrieve affiliates' data from from firestore

feat: added firbase in client and admin

---

frontend/client/src/Pages/PartnersForm/AffiliatePartners/Affiliate.jsx
frontend/client/src/Pages/PartnersForm/ReferralPartners/Referral.jsx

- Include API integration through which a post request is made for data generated from client inputs.
- Changes exist in **Affiliate.jsx** and **Referral.jsx**
- Loading, Loaded and Error states exist. Each state produces a different pop up on the screen.
- The Error state redirect back to the form
- The Loaded state has a button. On click redirects to home page.
https://linear.app/team-bevel/issue/FRO-37/build-a-referral-page
https://linear.app/team-bevel/issue/FRO-55/build-an-affiliate-page

feat(FRO-37/FRO-55): Added API Integration for the referral and affiliate pages

---

frontend/admin/src/component/ComplaintPage/ComplaintPageLayout.jsx
frontend/admin/src/component/UserComplaintsComponent/card/Card.jsx

- fixes cancel button
- changes 'resolve' status to 'unresolved'

Feat admin login

---

frontend/client/src/Pages/HistoricalCurrencyExchange/components/AmountInput.jsx
frontend/client/src/Pages/HistoricalCurrencyExchange/components/Top.jsx

This PR contains the following:
- bug fixes on the historical currency page
- Added geo-location functionality to the base currency on the conversion bar
- add drop down functionality to list all currencies available

fix: breaking changes to historical currency page

---

frontend/client/src/Pages/CurrencyProfile/chart/Chart.jsx

This PR improves the chart matching the chart to changing url

improve: set url path as a dependency

---

backend/street_rates_telegram_bot/testing.py

Added ability to list all the available ISO-CODES.
Added the ability to convert with amount from one currency to another.

Added more Fuctionality to the telegram bot

---

frontend/admin/src/pages/CreateCurrency/CreateCurrency.jsx
frontend/admin/src/store/actions/rateActions.js

feat: ratesAction

---

backend/app/api/v1/password_email_reset.py

…I added some comments to better understand the reset_password and created a dummy email for seeing the inbox

BAC-48/ Bug fix

---

frontend/admin/src/pages/CreateCurrency/CreateCurrency.jsx

fix: currency

---

backend/app/api/v1/api_service.py

Updated the rates service to stop getting USD rates because it is the base currency.

updated rates service

---

frontend/client/src/Pages/CurrencyProfile/CurrencyProfile.jsx
frontend/client/src/Pages/Glossary/Glossary.jsx
frontend/client/src/Pages/Home/Home.jsx
frontend/client/src/Pages/Home/components/Table2.jsx
frontend/client/src/Pages/News/components/HorizontalNewsCard.jsx

Improve: Dark mode Redesign

---

frontend/admin/src/component/MenuDrop/MenuDrop.jsx
frontend/admin/src/pages/CreateCurrency/AddRatesForm.jsx
frontend/admin/src/pages/CreateCurrency/AddRatesModal.jsx
frontend/admin/src/pages/CreateCurrency/CreateCurrency.jsx
frontend/admin/src/shared/Input.jsx

I implemented Add rate functionality to the admin side
https://user-images.githubusercontent.com/29485257/206950092-0ef9d638-4b99-4595-b7e1-41278a115566.mp4

Feat:Add rates functionality to the admin side

---

frontend/client/src/components/NavComponent.jsx

- fixes margin space on navbar logo

style: fixes margin on navbar logo

---

frontend/client/src/Pages/Home/Liverates.jsx

Fix: Dark mode redesign for live rates

---

frontend/client/src/Pages/Home/Liverates.jsx

Fix: liverates menu text

---

frontend/client/src/Pages/BoardOfDirectors/BoardOfDirectors.jsx
frontend/client/src/Pages/FaqOverview/FaqOverview.styled.js
frontend/client/src/Pages/Home/Liverates.jsx
frontend/client/src/Pages/PrivacyPolicy/PrivacyPolicy.js
frontend/client/src/components/Footer.jsx
frontend/client/src/components/home/Table.jsx

fix: footer links

---

frontend/client/src/Pages/About/components/Download.jsx

Fix new link
